required_resources:
   roberta-base:  "roberta-base"
   huggingface: "huggingface"
remote_zoo_dir: "./local_models_zoo"
load_from_zoo_use_remote: false
resource_dir: "/path_to_save_results/resources_enternal"
push_to_remote_zoo: false
push_to_local_zoo: true

merger:
  exclude_param_regex: ['.*pre_classifier.*','.*classifier.*']

  regmean_mean: true
  gram_n_example: 1000
  gram_version: "h_1000_0726_fix"


seed: 1
main_output_dir: '/path_to_save_results/runs/glue-roberta_base/regmean'
default_model_args:
  model_name: "roberta-base"
  version: 1
  zoo_filter:
    version: 1
    seed: 1
  do_lower_case: false
  per_device_train_batch_size: 16

tokenizer: "roberta-base"
model_type: roberta-base
